"""Lab Overview skill — regenerate LAB_DATA_OVERVIEW.md and DATA_MANIFEST.yaml from the catalog DB."""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime
from typing import Any, Dict, List

import yaml

from dm_agent.base_skill import BaseSkill, RunContext, SkillResult

logger = logging.getLogger(__name__)


class LabOverviewSkill(BaseSkill):
    name = "lab_overview"
    description = "Regenerate LAB_DATA_OVERVIEW.md from all cataloged datasets in the DB"
    phase = "report"

    def run(self, context: RunContext) -> SkillResult:
        cfg = self.get_config(context.config)
        output_path = cfg.get(
            "output_path",
            os.path.join(os.path.dirname(context.config.database_path), "LAB_DATA_OVERVIEW.md"),
        )

        datasets = context.db.get_all_datasets()
        cataloged = [d for d in datasets if d["status"] == "cataloged"]

        if not cataloged:
            return SkillResult(success=True, message="No cataloged datasets — overview not updated")

        lines = self._build_overview(cataloged, context)
        with open(output_path, "w") as f:
            f.write("\n".join(lines))

        # Also generate compact DATA_MANIFEST.yaml for Claude Code quick lookups
        manifest_path = cfg.get(
            "manifest_path",
            os.path.join(os.path.dirname(output_path), "DATA_MANIFEST.yaml"),
        )
        manifest = self._build_manifest(cataloged, context)
        with open(manifest_path, "w") as f:
            yaml.dump(manifest, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

        logger.info(f"Lab overview written to {output_path} ({len(cataloged)} datasets)")
        logger.info(f"Data manifest written to {manifest_path}")
        return SkillResult(
            success=True,
            message=f"Overview updated: {len(cataloged)} datasets → {output_path}",
            data={"path": output_path, "manifest_path": manifest_path, "datasets": len(cataloged)},
        )

    # ------------------------------------------------------------------
    # Overview builder
    # ------------------------------------------------------------------

    def _build_overview(self, datasets: List[Dict[str, Any]], context: RunContext) -> List[str]:
        lab = context.config.lab
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        lines = []

        # Header
        lines += [
            f"# {lab.get('name', 'Lab')} — Data Overview",
            "",
            f"**Generated:** {now} by DM Agent",
            f"**Lab:** {lab.get('name', '')}",
            f"**PI:** {lab.get('pi', '')}",
            f"**Storage:** {', '.join(t.path for t in (context.config.scan_targets or []))}",
            "",
            "---",
            "",
        ]

        # Summary table
        lines += ["## Summary", ""]
        lines += ["| Dataset | Data Types | Size | Files | Subjects | Modalities | Organization | BIDS | Cataloged |"]
        lines += ["|---------|-----------|------|-------|----------|------------|-------------|------|-----------|"]
        total_size = 0
        total_files = 0
        total_subjects = 0
        for d in datasets:
            size = d.get("total_size_bytes") or 0
            files = d.get("total_files") or 0
            subjects = d.get("total_subjects") or 0
            total_size += size
            total_files += files
            total_subjects += subjects
            modalities = json.loads(d.get("modalities") or "[]")
            project_cfg = context.config.projects.get(d["dataset_name"])
            data_types = project_cfg.data_types if project_cfg else modalities or ["unknown"]
            lines.append(
                f"| [{d['dataset_name']}](#{d['dataset_name'].lower().replace(' ','-')}-dataset) "
                f"| {', '.join(data_types)} "
                f"| {self._human_size(size)} "
                f"| {files:,} "
                f"| {subjects:,} "
                f"| {', '.join(modalities)} "
                f"| {d.get('organization_scheme','?')} "
                f"| {'Yes' if d.get('bids_compliant') else 'No'} "
                f"| {(d.get('cataloged_at') or '')[:10]} |"
            )
        lines += [
            f"| **Total** | | **{self._human_size(total_size)}** | **{total_files:,}** | **{total_subjects:,}** | | | | |",
            "",
            "---",
            "",
        ]

        # Per-dataset sections
        for d in datasets:
            lines += self._dataset_section(d, context)
            lines += ["---", ""]

        lines += [
            "*This file is auto-generated by the DM Agent lab_overview skill.*",
            "*Do not edit manually — changes will be overwritten on the next run.*",
        ]
        return lines

    def _dataset_section(self, d: Dict[str, Any], context: RunContext) -> List[str]:
        name = d["dataset_name"]
        lines = [f"## {name} Dataset", ""]

        # Basic info
        modalities = json.loads(d.get("modalities") or "[]")
        project_cfg = context.config.projects.get(name)
        data_types = project_cfg.data_types if project_cfg else modalities or ["unknown"]
        description = project_cfg.description if project_cfg else ""

        lines += [
            f"**Path:** `{d['root_path']}`",
            f"**Description:** {description}",
            f"**Data types:** {', '.join(data_types)}",
            f"**Size:** {self._human_size(d.get('total_size_bytes') or 0)} "
            f"| **Files:** {(d.get('total_files') or 0):,} "
            f"| **Subjects:** {d.get('total_subjects') or '—'}",
            f"**Organization:** {d.get('organization_scheme','unknown')} "
            f"| **BIDS:** {'Yes' if d.get('bids_compliant') else 'No'} "
            f"| **Raw:** {'Yes' if d.get('has_raw') else 'No'} "
            f"| **Preprocessed:** {'Yes' if d.get('has_preprocessed') else 'No'} "
            f"| **Derivatives:** {'Yes' if d.get('has_derivatives') else 'No'}",
            "",
        ]

        # Claude summary
        if d.get("summary"):
            lines += ["### Summary", "", d["summary"], ""]

        # Per-modality breakdown table
        mod_stats = context.db.get_modality_stats(d["id"])
        if mod_stats:
            lines += self._modality_table(mod_stats)

        # Directory table
        entries = context.db.get_catalog_entries(d["id"])
        if entries:
            lines += self._directory_table(entries)

        # Recommendations
        recs = json.loads(d.get("recommendations") or "[]")
        if recs:
            # Handle both old format (list) and new format (dict with recommendations key)
            rec_list = recs if isinstance(recs, list) else recs.get("recommendations", [])
            if rec_list:
                lines += self._recommendations_section(rec_list)

        return lines

    def _modality_table(self, mod_stats: List[Dict[str, Any]]) -> List[str]:
        lines = ["### Modality Breakdown", ""]
        lines += ["| Modality | Subjects | Files | Size | Dirs | Data Stages | Description |"]
        lines += ["|----------|----------|-------|------|------|-------------|-------------|"]
        for ms in mod_stats:
            stages = json.loads(ms.get("data_stages") or "[]")
            subjects = json.loads(ms.get("subject_list") or "[]")
            desc = (ms.get("description") or "—")
            # Truncate long descriptions
            if len(desc) > 80:
                desc = desc[:77] + "..."
            lines.append(
                f"| {ms['modality']} "
                f"| {ms['subject_count']} "
                f"| {ms['file_count']:,} "
                f"| {self._human_size(ms['size_bytes'] or 0)} "
                f"| {ms['dir_count']} "
                f"| {', '.join(stages)} "
                f"| {desc} |"
            )
        lines.append("")

        # Subject lists per modality (collapsible details)
        has_subjects = any(
            json.loads(ms.get("subject_list") or "[]") for ms in mod_stats
        )
        if has_subjects:
            lines += ["<details>", "<summary>Subject lists per modality</summary>", ""]
            for ms in mod_stats:
                subjects = json.loads(ms.get("subject_list") or "[]")
                if subjects:
                    lines += [
                        f"**{ms['modality']}** ({len(subjects)} subjects):",
                        "",
                        "```",
                        ", ".join(subjects),
                        "```",
                        "",
                    ]
            lines += ["</details>", ""]

        return lines

    def _directory_table(self, entries: List[Dict[str, Any]]) -> List[str]:
        lines = ["### Directory Structure", ""]
        lines += ["| Path | Depth | Type | Stage | Modality | Files | Size | Sample Files |"]
        lines += ["|------|-------|------|-------|----------|-------|------|-------------|"]
        for e in entries:
            sample = json.loads(e.get("sample_files") or "[]")
            sample_str = ", ".join(f"`{f}`" for f in sample[:3])
            if len(sample) > 3:
                sample_str += f" +{len(sample)-3} more"
            lines.append(
                f"| `{e['rel_path']}` "
                f"| {e['depth']} "
                f"| {e.get('entry_type','?')} "
                f"| {e.get('data_stage','?')} "
                f"| {e.get('modality') or '—'} "
                f"| {e.get('file_count',0):,} "
                f"| {self._human_size(e.get('size_bytes') or 0)} "
                f"| {sample_str} |"
            )
        lines.append("")
        return lines

    def _recommendations_section(self, recs: List[Dict[str, Any]]) -> List[str]:
        lines = ["### Recommendations", ""]
        priority_icon = {"high": "🔴", "medium": "🟡", "low": "🟢"}
        for i, r in enumerate(recs, 1):
            icon = priority_icon.get(r.get("priority", "").lower(), "•")
            lines.append(f"{i}. {icon} **[{r.get('priority','').upper()}]** {r.get('action','')}")
            if r.get("reason"):
                lines.append(f"   - *Reason:* {r['reason']}")
            if r.get("example"):
                example = r["example"].replace("\n", " ")
                lines.append(f"   - *Example:* `{example}`")
        lines.append("")
        return lines

    def _build_manifest(
        self, datasets: List[Dict[str, Any]], context: RunContext
    ) -> Dict[str, Any]:
        """Build a compact YAML manifest for Claude Code quick lookups.

        The manifest is small enough (~3-5 KB) to be read directly by Claude
        Code without running any CLI command, enabling instant answers to
        questions like "which datasets have structural connectivity data?".
        """
        lab = context.config.lab
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        ds_entries = {}
        total_size = 0
        total_subjects = 0
        for d in datasets:
            name = d["dataset_name"]
            size = d.get("total_size_bytes") or 0
            subjects = d.get("total_subjects") or 0
            total_size += size
            total_subjects += subjects

            # Per-modality breakdown
            mod_stats = context.db.get_modality_stats(d["id"])
            modalities = {}
            for ms in mod_stats:
                mod_entry = {
                    "subjects": ms["subject_count"],
                    "files": ms["file_count"],
                    "size": self._human_size(ms["size_bytes"] or 0),
                }
                desc = (ms.get("description") or "").strip()
                if desc:
                    # Keep description concise — first sentence only
                    first_sentence = desc.split(". ")[0]
                    if len(first_sentence) > 120:
                        first_sentence = first_sentence[:117] + "..."
                    mod_entry["desc"] = first_sentence
                stages = json.loads(ms.get("data_stages") or "[]")
                if stages:
                    mod_entry["stages"] = stages
                key_dirs = json.loads(ms.get("key_dirs") or "[]")
                if key_dirs:
                    mod_entry["key_dirs"] = key_dirs[:3]
                modalities[ms["modality"]] = mod_entry

            ds_entry = {
                "path": d["root_path"],
                "size": self._human_size(size),
                "total_subjects": subjects,
                "organization": d.get("organization_scheme", "unknown"),
                "has_raw": bool(d.get("has_raw")),
                "has_preprocessed": bool(d.get("has_preprocessed")),
                "has_derivatives": bool(d.get("has_derivatives")),
                "bids": bool(d.get("bids_compliant")),
            }
            # Add summary — keep it short
            summary = (d.get("summary") or "").strip()
            if summary:
                # First two sentences
                sentences = summary.split(". ")
                short = ". ".join(sentences[:2])
                if len(short) > 200:
                    short = short[:197] + "..."
                ds_entry["summary"] = short
            if modalities:
                ds_entry["modalities"] = modalities

            ds_entries[name] = ds_entry

        return {
            "generated": now,
            "lab": lab.get("name", ""),
            "pi": lab.get("pi", ""),
            "total_size": self._human_size(total_size),
            "total_datasets": len(datasets),
            "total_subjects": total_subjects,
            "datasets": ds_entries,
        }

    @staticmethod
    def _human_size(size_bytes: int) -> str:
        for unit in ["B", "KB", "MB", "GB", "TB"]:
            if abs(size_bytes) < 1024:
                return f"{size_bytes:.1f} {unit}"
            size_bytes /= 1024
        return f"{size_bytes:.1f} PB"
